### ISSUE TITLE
Add functions to allow easy recording of various variables

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/NeuroMLlite#9]
One for the long-term TODO list. It'll be good if we can include routines to allow easy recording of various variables from NeuroML models.

**Comment by pgleeson** [comment]
Already possible, see e.g. https://github.com/NeuroML/NeuroMLlite/blob/27e857cf5209667d282ca0e5753b31d4764711ec/examples/Example9.py#L38-L53. Anything that's there in a Lems model should be recordable
